# Generated by Django 4.1.7 on 2023-03-19 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('article_title', models.CharField(max_length=150)),
                ('target_language', models.CharField(max_length=3)),
                ('project_id', models.CharField(max_length=154, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_sentence', models.TextField()),
                ('translated_sentence', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='wiki_translation.project')),
            ],
        ),
    ]
